# prettier-ignore
version: "3.8"
services:
  mongodb:
    container_name: hail-indexer-mongodb
    image: mongo
    restart: unless-stopped
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - 27017:27017
    env_file:
      - .env
  redis:
    container_name: hail-indexer-redis
    image: redis
    restart: unless-stopped
    deploy: 
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - redis-cache:/data
    ports:
      - 10648:6379
    env_file:
      - .env
  indexer:
    container_name: hail-indexer-crawler
    build: ./
    restart: unless-stopped
    ports:
      - 8000:8080
    volumes:
      - logs:/app/src/logs
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env

volumes:
  data:
  logs:
  redis-cache: