// 1 day
const SECONDS_IN_DAY_IN_MILLISECONDS = 86_400_000;

// 365 days
const SECONDS_IN_YEAR_IN_MILLISECONDS = SECONDS_IN_DAY_IN_MILLISECONDS * 365;

export { SECONDS_IN_YEAR_IN_MILLISECONDS, SECONDS_IN_DAY_IN_MILLISECONDS };
